#!/bin/bash

#
# A simple script for creating cscope cross reference files.
#


input=${1:-"${PWD}"}
output=${2:-"${PWD}/.cscope"}

# set -x
mkdir -p ${output}
find ${input} -name "*.[CcHh]"\
   -o -name "*.cpp"\
   -o -name "*.cc"\
   -o -name "*.cxx"\
   -o -name "*.hpp" > ${output}/cscope.files
$(cd ${output}; cscope -b -q)
