#!bash
#
# bash completion support for cscope_db.py
#
#

_cscope_db_cmds_opts() {
    cscope_db.py --help | awk '/^[[:blank:]]{1,4}[a-z-]/ { print $1 }'
}

_cscope_db_complete()
{
    local cur prev words cword
    _init_completion || return

    case $prev in
        cscope_db.py | cs)
            COMPREPLY=( $( compgen -W '$(_cscope_db_cmds_opts)' -- "$cur" ) )
            return
            ;;
    esac
} && complete -F _cscope_db_complete cscope_db.py cs
