#!/bin/bash

# A simple script for creating cscope cross reference files.
#


DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. ${DIR}/_config_cli.sh

# set -x
mkdir -p ${output}
find ${input} -name "*.[CcHh]"\
   -o -name "*.cpp"\
   -o -name "*.cc"\
   -o -name "*.hpp" > ${output}/cscope.files
$(cd ${output}; cscope -b -q)
