#!/bin/bash

# A simple script for creating Cscope files for the Linux kernel's PPC code.
#

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. ${DIR}/_config_cli.sh

set -x
mkdir -p ${output}
find ${input} \
    -path "${input}/arch/*" ! -path "${input}/arch/powerpc*" -prune -o   \
    -path "${input}/Documentation*" -prune -o \
    -path "${input}/scripts*" -prune -o \
    -path "${input}/drivers*" -prune -o \
    -type f -name "*.[chxsS]" -print > ${output}/cscope.files
$(cd ${output}; cscope -b -q -k)
